---
- name: Main for RedHat OpenStack 13 (Queens) Install
  hosts: director 
  gather_facts: yes

  tasks:
          #- import_role:
          #    name: account
    - import_role:
        name: undercloud
    - import_role:
        name: overcloud
    - import_role:
        name: deploy

